# Generated by Django 4.1.7 on 2023-02-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('r_id', models.IntegerField()),
                ('r_password', models.CharField(max_length=8)),
                ('r_mail', models.EmailField(max_length=25)),
                ('r_mobile', models.IntegerField()),
                ('r_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=25)),
                ('p_price', models.IntegerField()),
                ('p_des', models.TextField(max_length=150)),
                ('p_qua', models.IntegerField()),
                ('p_status', models.CharField(max_length=30)),
                ('p_image', models.ImageField(upload_to='photos')),
                ('p_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totoalamount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=100)),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qua', models.IntegerField()),
                ('order_totalprice', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('productstatus', models.IntegerField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
