# Generated by Django 4.1.7 on 2023-02-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_category_name_category_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='category_name',
        ),
    ]
