# Generated by Django 4.1.7 on 2023-04-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_categoryname_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='r_id',
        ),
    ]
