# Generated by Django 4.1.7 on 2023-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_registration_r_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_des',
            field=models.TextField(max_length=300),
        ),
    ]
