# Generated by Django 4.1.7 on 2023-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_des',
            field=models.TextField(max_length=500),
        ),
    ]
